name: ecrpush


on:
  workflow_run:
    workflows: [ "newman" ]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted]
    environment:
      name: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-tag-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 716591628268.dkr.ecr.us-east-1.amazonaws.com/mypm
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR
          echo $ECR_REGISTRY/$ECR_REPOSITORY:stage
          docker build . -t $ECR_REPOSITORY:stage 
          docker push $ECR_REPOSITORY:stage
          echo "::set-output name=image::$ECR_REPOSITORY:stage"

      - name: Register new Task Definition
        id: register-task-def
        run: |
          # Replace the placeholder <TASK_DEFINITION> with your task definition file in JSON format.
          # Replace the placeholder <CONTAINER_NAME> with the name of the container in your task definition
          # And change <FAMILY_NAME> with the family name of your task definition
          TASK_DEFINITION=$(sed -e "s/<IMAGE_NAME>/$ECR_REPOSITORY:stage/" deployment/taskdef.json)
          echo "$TASK_DEFINITION" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json
          # Print the ARN of the newly registered task definition
          TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition tee1 --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "::set-output name=task-def-arn::$TASK_DEF_ARN"

      - name: Update Service
        run: |
          # Replace the placeholders <CLUSTER_NAME> and <SERVICE_NAME> with your AWS ECS Cluster and Service names
          aws ecs update-service --cluster tee --service blbablatee1 --task-definition ${{ steps.register-task-def.outputs.task-def-arn }}
          

      - name: Clear ECR credentials
        if: always()
        run: rm -rf ~/.docker/config.json
