name: ecrpush

on:
  workflow_run:
    workflows: [ "newman" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-tag-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 716591628268.dkr.ecr.us-east-1.amazonaws.com/mypm
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build . -t $ECR_REPOSITORY:$IMAGE_TAG 
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Clear ECR credentials
        if: always()
        run: rm -rf ~/.docker/config.json
